### ISSUE TITLE
XLPP Arduino libary files should at root folder

### ISSUE THREAD

**Issue by cdupont** [Waziup/xlpp#1]
Currently, this repo contains both Arduino and Go files.
It might be a problem to publish it as an Arduino library: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#is-my-git-repo-ok
"Your repo is OK if its root folder contains the file library.properties and the rest of the library source code".

I also think it would be easier to have the Arduino lib files at root for mounting the library as "git submodule" or "git subtree" in WaziDev-lib and other dependencies.

**Comment by j-forster** [comment]
The repository has now been split, see also https://github.com/Waziup/arduino-xlpp.
