### ISSUE TITLE
error message in decoding with xlpp.exe : unregistered xlpp type 0x32

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/xlpp#2]
Applying wazicloud actuator type object does not decode the message in wazidev (see picture for encoding and message below for decoding):

![wazicloud_xlpp_encoding_object](https://user-images.githubusercontent.com/62630067/108436135-2a234400-724b-11eb-86c2-f781fe9cd172.gif)

Error message:

E:\HTW\HTW-Vorlesungen\EDFS\LoRa-Uebung>xlpp -d ZXlKamIyeHZkWEl3SWpvaUkyWm1ZV0ZtWmlKOQ==
can not read xlpp: unregistered XLPP type 0x32

**Comment by j-forster** [comment]
This error has been traced to be a Base64 decoded text message that is send by Gateway when receiving actuation commands from the cloud. You can decode the Base64 Payoad (twice) to see the original JSON message.
