### ISSUE TITLE
README file: clear distinction between LPP and XLPP

### ISSUE THREAD

**Issue by cdupont** [Waziup/xlpp#4]
At the moment, it seems that the distinction between LPP and XLPP is not clear.
For instance, the Distance (type 130) is in the section "LPP", but it seems to be an XLPP type.

**Comment by j-forster** [comment]
The second table on the Readme file shows types that are not covered by the LPP spec, but are implemented by the [Arduino CayenneLPP library](https://github.com/ElectronicCats/CayenneLPP/blob/master/src/CayenneLPP.h#L24-L38). I am not sure if there is some official spec covering these types...

**Comment by cdupont** [comment]
Can you see this message on the forum: https://forum.waziup.io/t/error-data-not-published-to-wazicloud/125
It says "unknown type 130" so I supposed this type is not part of LPP.

**Comment by j-forster** [comment]
https://github.com/Waziup/xlpp/commit/a0b2e651320d59fc3034795423c8a6b680881196 This should be more clear now.
